[package]
name = "simple-game"
version = "0.1.0"
authors = ["Greg Tatum <tatum.creative@gmail.com>"]
edition = "2018"

[dependencies]
nes-core = { path = "../nes-core" }
colored = { workspace = true }
rand = { workspace = true }
sdl2 = { workspace = true, features = ["unsafe_textures"] }
